name: Build, lint, format

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install -D
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: lint
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: check
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: build
